### ISSUE TITLE
problem with sedchange

### ISSUE THREAD

**Issue by veronicas87** [rosalieb/serac#1]
Hi, i m trying to include sedchange in serac. Before to add the sedchange string in the model, i have no problem, the model is working well and i have good results, after using sedchage=c(XX), the model is not working. there are not outputs.
Do u have any suggestions? thanks a lot for the help.

**Comment by rosalieb** [comment]
Hello,
Just trying the easy trouble shooting options first:
-  Make sure you spell out 'sedchange' the proper way (in your message, you wrote 'sedchage').
-  Make sure you put the sedchange value as a numeric vector, and not some text, i.e., c(43, 55) and not c("43", "55").

If this did not work, try running the example included in the vignette:

```
# Install serac
devtools::install_github("rosalieb/serac", build_vignettes = TRUE)
library(serac)
# Create folders
dir.create(file.path(getwd(), 'Cores'), showWarnings = FALSE)
dir.create(file.path(paste0(getwd(),'/Cores'), 'serac_example_ALO09P12'), showWarnings = FALSE)
# Write in data
write.table(x = serac_example_ALO09P12, file = paste0(getwd(),'/Cores/serac_example_ALO09P12/serac_example_ALO09P12.txt'),col.names = T, row.names = F,sep="\t")
# Run the basic model
serac(name="serac_example_ALO09P12",coring_yr=2009,save_code=FALSE)
# Try adding some sedchange
serac(name="serac_example_ALO09P12",coring_yr=2009,save_code=FALSE, sedchange = 54)
serac(name="serac_example_ALO09P12",coring_yr=2009,save_code=FALSE, sedchange = 112)
```

If the example works, but you still cannot fix your code, please send me your formated input data file and the exact `serac()` code you wrote, and I will help troubleshoot. 
Best,
Rosalie

**Comment by veronicas87** [comment]
Hi,
Thanks a lot! I will running your example and if is not working, i will send u the code and input data file.
Thanks againg,
Best
Veronica

Inviato da iPhone

**Comment by rosalieb** [comment]
Closing this as I did not hear back from the user.
